name = "Nyamcraft"
author = "Lnvll"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c219c180832d34a47f29372ab906de613acd190acf6fdf15558ab856f99ad46f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
