name = "Nyamcraft"
author = "Lnvll"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eef2d9ead2411c0906ac33fa6375625e70b67479e182929049b04ecc2200cccb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
