name = "Nyamcraft"
author = "Lnvll"
version = "0.5.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00d2d3fa4ce7a79a0dbb2f84ef0cf95708914f63baa4391ba705cbb9d289428a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
