StartupEvents.registry('block', event => {
  event.create('currency:currencyblock')
    .displayName('Nyan Block')
    .soundType('amethyst')
    .fullBlock(false)
    .defaultCutout()
    .hardness(2)
    .resistance(1200)
    .requiresTool(true)
    .tagBlock('currency:nyanblock')
    .tagBlock('c:storage_blocks')
    .tagBlock('c:storage_blocks/nyanblock')
    .tagBlock('minecraft:beacon_base_blocks')
    //.tagBlock('minecraft:incorrect_for_gold_tool')
    .tagBlock('minecraft:incorrect_for_wooden_tool')
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    //.tagBlock('sable:super_heavy')
    //.setLootTableJson()
})

StartupEvents.registry('item', event => {
  event.create('currency:currencycoin')
    .displayName('Nyan coin')
    .maxStackSize(64)
    //.tooltip('Валюта в Нямперии')
    //.color(0, '#7b6389')
    //.color(1, '#978cbd')
    .tag('currency:nyancoin')
    .tag('c:gems')
    .tag('c:gems/nyancoin')
})