StartupEvents.registry('block', event => {
  event.create('currency:currencyblock')
    .displayName('Currency Block')
    .soundType('amethyst')
    .fullBlock(false)
    .defaultCutout()
    .hardness(2)
    .resistance(1200)
    .requiresTool(true)
    .tagBlock('currencycurrency:block')
    .tagBlock('c:storage_blocks')
    .tagBlock('c:storage_blocks/currencyblock')
    .tagBlock('minecraft:beacon_base_blocks')
    .tagBlock('minecraft:incorrect_for_gold_tool')
    .tagBlock('minecraft:incorrect_for_wooden_tool')
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .tagBlock('sable:super_heavy')
    //.setLootTableJson()
})

StartupEvents.registry('item', event => {
  event.create('currency:currencycoin')
    .displayName('Currency coin')
    .maxStackSize(64)
    //.color(0, '#7b6389')
    //.color(1, '#978cbd')
    .tag('currency:coin')
    .tag('c:gems')
    .tag('c:gems/currencycoin')
})

const $SoundEvents = Java.loadClass('net.minecraft.sounds.SoundEvents')
const $ParticleTypes = Java.loadClass('net.minecraft.core.particles.ParticleTypes')

StartupEvents.registry('fluid', event => {
  event.create('currency:currencium')
    .displayName('Currencium')
    .type(type => type
      .renderType(3)
      .stillTexture('minecraft:block/water_still')
      .flowingTexture('minecraft:block/water_flow')
      .tint(0x876c95)
      .fallDistanceModifier(0)
      .canPushEntity(true)
      .canSwim(true)
      .canDrown(true)
      .canExtinguish(true)
      .canConvertToSource(false)
      .pathType(9)
    )
})